trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    sudo apt install -y terraform 
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    az login --service-principal -u $(GITHUB_APPID) -p $(GITHUB_PASSWORD) --tenant $(GITHUB_TENANT)
    az account show | grep -i robert
  displayName: connect to azure

- task: DownloadSecureFile@1
  name: file_id_rsa
  displayName: 'download id_rsa'
  inputs:
    secureFile: 'id_rsa'

- script: |
    whoami
    sudo chown $USER:$USER $(file_id_rsa.secureFilePath)
    sudo chmod 600 $(file_id_rsa.secureFilePath)
    mkdir -p /home/$USER/.ssh
    echo -e "Host $(SHARE_IP)\n\tStrictHostKeyChecking no" > /home/$USER/.ssh/config
    sudo ln -s -t /home/$USER/.ssh/ $(file_id_rsa.secureFilePath)
    ssh $(SHARE_USER)@$(SHARE_IP) "echo test123"
  displayName: add authorization method for ssh

- script: |
    echo "this is text in test file" > file
    scp file $(SHARE_USER)@$(SHARE_IP):/home/$(SHARE_USER)/.
    ssh $(SHARE_USER)@$(SHARE_IP) "cat /home/$(SHARE_USER)/file"
  displayName: copy file

- script: |
    cd azure_training
    export ARM_CLIENT_ID=$(github_name)
    export ARM_CLIENT_SECRET=$(github_password)
    export ARM_SUBSCRIPTION_ID=$(github_sub_id)
    export ARM_TENANT_ID=$(github_tenant_id)
    terraform init
    terraform --version
    terraform plan
    terraform apply
    ls -la
  displayName: terraform usage
